language: python
notifications:
  irc: "irc.freenode.net#gplaycli"
python:
  - "2.7"
  - "pypy-5.3.1"
before_install: 
  - date
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: py.test
