dist: bionic
jobs:
  include:
  - stage: Unit tests
    language: python
    python: 3.7
    before_install:
    - sed -i "s/gmail_address=.*/gmail_address=$GMAIL_ADDR/g" gplaycli.conf
    - sed -i "s/gmail_password=.*/gmail_password=$GMAIL_PWD/g" gplaycli.conf
    - sed -i "s/token=.*/token=False/g" gplaycli.conf
    install: pip install .
    script: python -m pytest tests
env:
  global:
  - secure: d75Nt2qAQ127rBldohGXelcqZcJaS81ipFq7i3w33J3wUxmWuF25h3D49NdJ03iZp31NnRjEACfLJu2pYSHYmMU9dKmwyuaShd8jJ+rimZlwMtUjmqel9ArNPEEQaad8zNAF94Wrttft9pOAoKJJoV83UfJJJ8TRiNfyuBIX0mzuIxaNhqOAO6YT6l0FwXZf1GRu6L7w9VE6Fo1zGq+Iu3tPnOLkuRtTqe1+cgY+yyRTV0BAEzRDqIx47dXRDEvZmAoWOcI/zL3aBJF7vMG4CQurzF0Csuilm9QBWWGridvuDOUmAfGAZ/Zls+ZXqcLxm4fRvRRR1mptpM8XdNrPd6Me3NRBpxHooAXMInXGLtjVQMbVSA8zsfU1UaoyGuHjKOmgQJcu3FKZTVmx8gZudqgpraqc0502q4z6E3hpBRFzUgdhNz9hdKQeVkegaEhOQDdPGh4My5vLjNObLdUIM7Rh0P4UzoINO1ZlOdkNz+aot+NL4Q30G1IBZXhtHHivAJt0Zubmh74RY/TZRLwj21sYdGJKiyU86Fh9sdM5+Nnjyuynr6NOadgnXsQtVnD85nV2YZomPw6sj2KmTT0ZdInOuP7FJ63gcNN8VNKm9yWGKTjKchm6bkpsM6ujdzcqpGyQlTMextMDEh8Mo4VRvCTubMyKF9BBPu/JvRXnGeQ=
  - secure: gIEZBQM9sgJuQtoYDCfincbz5Xb6octzSGpHj/r1q7yc8oHm1/GVlzqNJEfHZQ410Y4dlQDVX1LU9GdAHnhE4Qtceb3omGJw5ngwM9erWaHUZW9rmbB9FVs3AoxevzAsyPP+48qAqpbh9MyfD/oY/7yvh8yzqoyAk57MAbaRxADpB8kAezMnFI9OS6WCxzux7WSf5OIniKURQj51cut5/yFYJgDKuUrjpJQSLjXMLTH4hfJ9cGGMGnQtNtnaACWfC7u52rV7wpptyfcindfk089KDXi7lgWqRNH8EskWz0gdxRPeKW1d9IwWJLE9ajwBOpS1LwqUueTF6JsUHImizZcAS1XCbmo0EZhyQxcTvQQGI+D+zOoxM0Js1PE2nSahuO98kaYNYUfg6Av63kLJNq5KXcH4/FTSpvNQrJIUPgoHzOoB1P9f2a5LLLqDcvs3F/lK6m1jjg4I9SXzRRmoNRQIDHnXCV2UeMcBLxBG3bH32lrCxVqLs9n/kYi7BZSX6FxTEcHv3sg4862KLv3Mn1j6vq/K3CHA3aaEp656ukQyJTUl5CuiUIDYLX7aEo7qnhQWzc1aKncvaXsFJsQkYB76+NszRo9w/TSDh6ZxHZhZ5z0X/maerSjjcpG0I7lz1n+8xmWax6BAgQ8u4KdwMSX2czohq3WvUmXJ1uIY78g=
