language: python
python:
- '2.7'
- pypy-5.3.1
before_install:
- date
install:
- pip install -r requirements.txt
script: py.test
env:
  global:
  - secure: pwRKtlFQCTV2kSP32sCykKVD4wW0IudFduG1C3IQ4nqWURRVr7klKvp/Dkmr62gvcTk5xKgpuzVqHGAd01L6dWjBncOZmAu9Kx2rU+k3PXNdYLn9GvjA0OZ5IWqF8V5/XIQP1R8qAEX27vMdy5wtUy3vBGDpvPLhrKR4/CGRLpu5opH2bvYgkSk+oclvWbhUrCa9OEbrHHqxna4jZppINGSP2LjVA4k3KJheSJauSHTvbWbVWaaKviuxJBmCaPncumcBefxoy4oDQdNC+RVSzUg+3prv83F5wCIl/t7fihrzTupyfVs7YzpGEStPdO+3mgRG6bkQZKE7g56fNlzpzon9PLR1uluBco44+LMn2q5Y9LqXwrX2+hikF79FXALPZbE4RDmX5ZHttjfNSbQXIlFTAlvTKlXdPpszQl9zfXFljU1ZwTzdQYHAJS6xf2pKSxCFrLJgOJascFyI1EVClco/90U/ZscGYK4cQtBY8nMHFlnsI2Nl4a6PDmjNR4H8XC7WH74oBFhB9IxXqgsQYpd8eMNT7cBHaTkI0firW+9ZnMZn3kGUidjRkSOM1POSKir0jiV6uXn5LMjT91dg2ZcHvtALaGVqEBckalk0d8bBE13NbDmK7NPQ/PmiVQmcndkWA9q5BB90rvJ5Ox07kdyrsWH8r3nsteJgl7wlSFI=
  - secure: Asr8GkiGG5W6jVL8cRpDl414iRqjMecYNYgwx2e2JKd9JMLKGbTVscqlgUwcYB1q4+Q1DvY5qZXaVFqnAvknnbLGG3vgU9kGcsRfhZTd8+2/2ewPYVNipWQYPOQWovJ4CRZoGJCDFXppfTK3/NCjDSnR9UH0NmBFJO6GzUOtS6dnns5HRGzYplTtRKDIlOgU5BcbTBPiqX9wtEDFAN7vblif1ZDxIa0mVDC+jHmG8/cNp/ZeAcmoDWb9VlgAL4C7eromh6KswhI38655UjOc7Tdr5cgmEYXIricANmaQ4g3HkcXeQYJl7vP401+QPwAlRuODPbaR3TzPJLpyJFpYJb1oMmDU836F3fMmUyeT/5QkQ+ws0BEQL9ORVHhmA2VZXrGxnki2DVMb32HPOXcIJ+yVA4NasYiIVlXtCzioCALjifSpbq4xhpZn9jcBKI6yt0I9YfW29n1QDKGYPMPu3N/Vd4E4fVYRUSFblxDUkqfcet11l54yCCK9QKnFCqd1FAHzb6NnuaZ+Su+qgXpbPgnRFSHs2+qWGSkjSSDJ52+cA7oq4r4w42lV/QzJHEkdoDh0fBBH3W86aPdZlFyUH6m2FIdfF8s2xhww7MHnNVx4uTNNqpxSsqSrXUsz5Jk1anZ0huA0QZqSnlvMKe7VbmARXwgGp0kfYYTODvdrFq0=
